config/routes.rb
Rails.application.routes.draw do
  resources :lesson_payments
  resources :bookings
  resources :schedules
  resources :clients
  resources :trainers
  resources :lessons
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord

    has_many :trainers, :through => :bookings
  
    has_many :clients, :through => :bookings
    
    has_many :bookings, :inverse_of => :lessons
    accepts_nested_attributes_for :bookings
    
    mount_uploader :image, LessonUploader
    
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show]
def index
    @lessons = Lesson.paginate(:page => params[:page], :per_page => 6).order('sort ASC')
  end
def show
    @others = Lesson.paginate(:page => params[:page], :per_page => 4).order('sort ASC')
  end
private
def set_lesson
    @lesson = Lesson.find(params[:id])
end
end

# class LessonsController < ApplicationController
#   before_action :set_lesson, only: %i[ show edit update destroy ]

#   # GET /lessons or /lessons.json
#   def index
#     @lessons = Lesson.all
#   end

#   # GET /lessons/1 or /lessons/1.json
#   def show
#   end

#   # GET /lessons/new
#   def new
#     @lesson = Lesson.new
#   end

#   # GET /lessons/1/edit
#   def edit
#   end

#   # POST /lessons or /lessons.json
#   def create
#     @lesson = Lesson.new(lesson_params)

#     respond_to do |format|
#       if @lesson.save
#         format.html { redirect_to @lesson, notice: "Lesson was successfully created." }
#         format.json { render :show, status: :created, location: @lesson }
#       else
#         format.html { render :new, status: :unprocessable_entity }
#         format.json { render json: @lesson.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # PATCH/PUT /lessons/1 or /lessons/1.json
#   def update
#     respond_to do |format|
#       if @lesson.update(lesson_params)
#         format.html { redirect_to @lesson, notice: "Lesson was successfully updated." }
#         format.json { render :show, status: :ok, location: @lesson }
#       else
#         format.html { render :edit, status: :unprocessable_entity }
#         format.json { render json: @lesson.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /lessons/1 or /lessons/1.json
#   def destroy
#     @lesson.destroy
#     respond_to do |format|
#       format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
#       format.json { head :no_content }
#     end
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_lesson
#       @lesson = Lesson.find(params[:id])
#     end

#     # Only allow a list of trusted parameters through.
#     def lesson_params
#       params.require(:lesson).permit(:image, :title, :duration, :cost, :category, :language, :level, :description)
#     end
# end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.number_field :cost %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lessons</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Duration</th>
      <th>Cost</th>
      <th>Category</th>
      <th>Language</th>
      <th>Level</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.image %></td>
        <td><%= lesson.title %></td>
        <td><%= lesson.duration %></td>
        <td><%= lesson.cost %></td>
        <td><%= lesson.category %></td>
        <td><%= lesson.language %></td>
        <td><%= lesson.level %></td>
        <td><%= lesson.description %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @lesson.image %>
</p>

<p>
  <strong>Title:</strong>
  <%= @lesson.title %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @lesson.duration %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @lesson.cost %>
</p>

<p>
  <strong>Category:</strong>
  <%= @lesson.category %>
</p>

<p>
  <strong>Language:</strong>
  <%= @lesson.language %>
</p>

<p>
  <strong>Level:</strong>
  <%= @lesson.level %>
</p>

<p>
  <strong>Description:</strong>
  <%= @lesson.description %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>
<%= link_to custom_url(:lesson_id => @lesson.id), class: "course-btn" do %><i class="fa fa-calendar-plus-o"></i> Book This Lesson<% end %>