config/routes.rb
Rails.application.routes.draw do
  resources :lesson_payments
  resources :bookings
  resources :schedules
  resources :clients
  resources :trainers
  resources :lessons
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lesson_payment.rb
class LessonPayment < ApplicationRecord
    belongs_to :account, :inverse_of => :lesson_payments
    accepts_nested_attributes_for :account
     
    belongs_to :booking, :inverse_of => :lesson_payments
    accepts_nested_attributes_for :booking
end

app/controllers/lesson_payments_controller.rb
class LessonPaymentsController < ApplicationController
  before_action :set_lesson_payment, only: %i[ show edit update destroy ]

  # GET /lesson_payments or /lesson_payments.json
  def index
    @lesson_payments = LessonPayment.all
  end

  # GET /lesson_payments/1 or /lesson_payments/1.json
  def show
  end

  # GET /lesson_payments/new
  def new
    @lesson_payment = LessonPayment.new
  end

  # GET /lesson_payments/1/edit
  def edit
  end

  # POST /lesson_payments or /lesson_payments.json
  def create
    @lesson_payment = LessonPayment.new(lesson_payment_params)

    respond_to do |format|
      if @lesson_payment.save
        format.html { redirect_to @lesson_payment, notice: "Lesson payment was successfully created." }
        format.json { render :show, status: :created, location: @lesson_payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lesson_payments/1 or /lesson_payments/1.json
  def update
    respond_to do |format|
      if @lesson_payment.update(lesson_payment_params)
        format.html { redirect_to @lesson_payment, notice: "Lesson payment was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson_payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lesson_payments/1 or /lesson_payments/1.json
  def destroy
    @lesson_payment.destroy
    respond_to do |format|
      format.html { redirect_to lesson_payments_url, notice: "Lesson payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson_payment
      @lesson_payment = LessonPayment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_payment_params
      params.require(:lesson_payment).permit(:payment_number, :status, :date, :cost, :service, :booking_id, :account_id)
    end
end

app/helpers/lesson_payments_helper.rb
module LessonPaymentsHelper
end

app/views/lesson_payments/_form.html.erb
<%= form_with(model: lesson_payment) do |form| %>
  <% if lesson_payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson_payment.errors.count, "error") %> prohibited this lesson_payment from being saved:</h2>

      <ul>
        <% lesson_payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :payment_number %>
    <%= form.text_field :payment_number %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.number_field :cost %>
  </div>

  <div class="field">
    <%= form.label :service %>
    <%= form.text_field :service %>
  </div>

  <div class="field">
    <%= form.label :booking_id %>
    <%= form.number_field :booking_id %>
  </div>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.number_field :account_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lesson_payments/edit.html.erb
<h1>Editing Lesson Payment</h1>

<%= render 'form', lesson_payment: @lesson_payment %>

<%= link_to 'Show', @lesson_payment %> |
<%= link_to 'Back', lesson_payments_path %>

app/views/lesson_payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lesson Payments</h1>

<table>
  <thead>
    <tr>
      <th>Payment number</th>
      <th>Status</th>
      <th>Date</th>
      <th>Cost</th>
      <th>Service</th>
      <th>Booking</th>
      <th>Account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lesson_payments.each do |lesson_payment| %>
      <tr>
        <td><%= lesson_payment.payment_number %></td>
        <td><%= lesson_payment.status %></td>
        <td><%= lesson_payment.date %></td>
        <td><%= lesson_payment.cost %></td>
        <td><%= lesson_payment.service %></td>
        <td><%= lesson_payment.booking_id %></td>
        <td><%= lesson_payment.account_id %></td>
        <td><%= link_to 'Show', lesson_payment %></td>
        <td><%= link_to 'Edit', edit_lesson_payment_path(lesson_payment) %></td>
        <td><%= link_to 'Destroy', lesson_payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson Payment', new_lesson_payment_path %>

app/views/lesson_payments/new.html.erb
<h1>New Lesson Payment</h1>

<%= render 'form', lesson_payment: @lesson_payment %>

<%= link_to 'Back', lesson_payments_path %>

app/views/lesson_payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payment number:</strong>
  <%= @lesson_payment.payment_number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @lesson_payment.status %>
</p>

<p>
  <strong>Date:</strong>
  <%= @lesson_payment.date %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @lesson_payment.cost %>
</p>

<p>
  <strong>Service:</strong>
  <%= @lesson_payment.service %>
</p>

<p>
  <strong>Booking:</strong>
  <%= @lesson_payment.booking_id %>
</p>

<p>
  <strong>Account:</strong>
  <%= @lesson_payment.account_id %>
</p>

<%= link_to 'Edit', edit_lesson_payment_path(@lesson_payment) %> |
<%= link_to 'Back', lesson_payments_path %>