config/routes.rb
Rails.application.routes.draw do
  resources :lesson_payments
  resources :bookings
  resources :schedules
  resources :clients
  resources :trainers
  resources :lessons
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/trainer.rb
class Trainer < ApplicationRecord

# Tenant Of
belongs_to :account, :inverse_of => :trainers
accepts_nested_attributes_for :account

belongs_to :user, :inverse_of => :trainers
accepts_nested_attributes_for :user

has_many :bookings, dependent: :destroy, :inverse_of => :trainer
accepts_nested_attributes_for :bookings

has_many :lessons, :through => :bookings

has_many :lesson_payments, :through => :bookings

has_many :schedules, dependent: :destroy, :inverse_of => :trainer
accepts_nested_attributes_for :schedules

mount_uploader :photo, TrainerUploader

def name 
  "#{first_name} #{last_name}"
end

def email
  User.find_by_id(self.user_id)
end

end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: %i[ show edit update destroy ]

  # GET /trainers or /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1 or /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers or /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: "Trainer was successfully created." }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1 or /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: "Trainer was successfully updated." }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1 or /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: "Trainer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trainer_params
      params.require(:trainer).permit(:photo, :first_name, :last_name, :phone, :bio, :experience, :user_id, :account_id)
    end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/_form.html.erb
<%= form_with(model: trainer) do |form| %>
  <% if trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
        <% trainer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :experience %>
    <%= form.text_field :experience %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.number_field :account_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainers</h1>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Bio</th>
      <th>Experience</th>
      <th>User</th>
      <th>Account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each do |trainer| %>
      <tr>
        <td><%= trainer.photo %></td>
        <td><%= trainer.first_name %></td>
        <td><%= trainer.last_name %></td>
        <td><%= trainer.phone %></td>
        <td><%= trainer.bio %></td>
        <td><%= trainer.experience %></td>
        <td><%= trainer.user_id %></td>
        <td><%= trainer.account_id %></td>
        <td><%= link_to 'Show', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainer', new_trainer_path %>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <%= @trainer.photo %>
</p>

<p>
  <strong>First name:</strong>
  <%= @trainer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @trainer.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @trainer.phone %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @trainer.bio %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @trainer.experience %>
</p>

<p>
  <strong>User:</strong>
  <%= @trainer.user_id %>
</p>

<p>
  <strong>Account:</strong>
  <%= @trainer.account_id %>
</p>

<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>